config/routes.rb
NavMap::Application.routes.draw do
  resources :systems do
    resources :nav_entries
  end

  root :to => "systems#index"

end

app/models/nav_entry.rb
class NavEntry < ActiveRecord::Base
	belongs_to :system
	belongs_to :parent, :class_name => "NavEntry"
	
	has_many :children, :class_name => "NavEntry",
		:foreign_key => "parent_id"
	
	validates :system, :presence => true
	validates :seq, :presence => true, 
    :uniqueness => {:scope => [:system_id, :parent_id]}
	validates :content, :presence => true, 
    :uniqueness => {:scope => [:system_id, :parent_id]}
end

app/models/system.rb
class System < ActiveRecord::Base
	has_many :nav_entries
	
  validates :name, :presence => true  
	validates :version, :presence => true, 
		:uniqueness => {:scope => :name}
	
    def roots
      self.nav_entries.where("parent_id IS NULL").order("seq ASC")
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/nav_entries_controller.rb
class NavEntriesController < ApplicationController
  # GET /nav_entries
  # GET /nav_entries.xml
  def index
    get_system
    @nav_entries = NavEntry.where("system_id = ? AND parent_id IS NULL", @system).order("seq ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @nav_entries }
    end
  end

  # GET /nav_entries/1
  # GET /nav_entries/1.xml
  def show
    get_system
    @nav_entry = NavEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @nav_entry }
    end
  end

  # GET /nav_entries/new
  # GET /nav_entries/new.xml
  def new
    get_system
    @parent = NavEntry.find(params[:parent_id]) unless params[:parent_id].nil?
    @nav_entry = NavEntry.new(:system => @system, :parent => @parent)
    get_parents

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @nav_entry }
    end
  end

  # GET /nav_entries/1/edit
  def edit    
    get_system
    @nav_entry = NavEntry.find(params[:id])
    get_parents
  end

  # POST /nav_entries
  # POST /nav_entries.xml
  def create    
    get_system
    @nav_entry = NavEntry.new(params[:nav_entry])
    get_parents

    respond_to do |format|
      if @nav_entry.save
        format.html { redirect_to(system_path(@system), :notice => 'Nav entry was successfully created.') }
        format.xml  { render :xml => @nav_entry, :status => :created, :location => @nav_entry }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @nav_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /nav_entries/1
  # PUT /nav_entries/1.xml
  def update
    get_system
    @nav_entry = NavEntry.find(params[:id])
    get_parents

    respond_to do |format|
      if @nav_entry.update_attributes(params[:nav_entry])
        format.html { redirect_to(system_nav_entry_path(@system, @nav_entry), :notice => 'Nav entry was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @nav_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /nav_entries/1
  # DELETE /nav_entries/1.xml
  def destroy    
    get_system
    @nav_entry = NavEntry.find(params[:id])
    @nav_entry.destroy

    respond_to do |format|
      format.html { redirect_to(system_url(@system)) }
      format.xml  { head :ok }
    end
  end
  
  private
  def get_system
    @system = System.find(params[:system_id])
  end
  
  def get_parents
    # if @nav_entry.nil? || @nav_entry.id.nil?
    #   @parents = NavEntry.where("system_id = ?", @system
    #     ).order("parent_id ASC, seq ASC")
    # else
    #   @parents = NavEntry.where("system_id = ? AND id <> ?", @system, @nav_entry
    #     ).order("parent_id ASC, seq ASC")
    # end
    
    @parents = []
    @system.roots.each do |n|      
      add_self_and_children(n)
    end
  end
  
  def add_self_and_children(nav_entry, indent = '')
    unless @nav_entry == nav_entry
      @parents << [indent + nav_entry.content, nav_entry.id]
      indent += '>'
      nav_entry.children.each do |n|
        add_self_and_children(n, indent)
      end
    end
  end
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  # GET /systems
  # GET /systems.xml
  def index
    @systems = System.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @systems }
    end
  end

  # GET /systems/1
  # GET /systems/1.xml
  def show
    @system = System.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @system }
    end
  end

  # GET /systems/new
  # GET /systems/new.xml
  def new
    @system = System.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @system }
    end
  end

  # GET /systems/1/edit
  def edit
    @system = System.find(params[:id])
  end

  # POST /systems
  # POST /systems.xml
  def create
    @system = System.new(params[:system])

    respond_to do |format|
      if @system.save
        format.html { redirect_to(@system, :notice => 'System was successfully created.') }
        format.xml  { render :xml => @system, :status => :created, :location => @system }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @system.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /systems/1
  # PUT /systems/1.xml
  def update
    @system = System.find(params[:id])

    respond_to do |format|
      if @system.update_attributes(params[:system])
        format.html { redirect_to(@system, :notice => 'System was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @system.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /systems/1
  # DELETE /systems/1.xml
  def destroy
    @system = System.find(params[:id])
    @system.destroy

    respond_to do |format|
      format.html { redirect_to(systems_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nav_entries_helper.rb
module NavEntriesHelper
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Systems Navigation Mapper</title>
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="top_navigation">
    <%= render_navigation %>
  </div>
  <%= yield %>

</body>
</html>

app/views/nav_entries/_form.html.erb
<%= semantic_form_for [@system, @nav_entry] do |f| %>
  <% f.inputs  do %>
    <%= f.input :system_id, :as => :hidden %>
    <%= f.input :system, :input_html => { :disabled => true } %>
    <%= f.input :parent, :collection => @parents %>
    <%= f.input :seq %>
    <%= f.input :content %>
    <%= f.input :description %>
  <% end%>
  <%= f.buttons %>
<% end %>

app/views/nav_entries/edit.html.erb
<%= link_to 'Back', system_path(@system) %> |
<%= link_to 'Destroy', system_nav_entry_path(@system, @nav_entry), :confirm => 'Are you sure?', :method => :delete %>

<h1>Editing Nav Entry</h1>

<%= render 'form' %>

app/views/nav_entries/index.html.erb
<h1>Listing Nav Entries for <%= @system.name + ' (Version: ' + @system.version + ')' %></h1>

<table>
  <tr>
    <th>Seq</th>
    <th>Content</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nav_entries.each do |nav_entry| %>
  <tr>
    <td><%= nav_entry.seq %></td>
    <td><%= nav_entry.content %></td>
    <td><%= nav_entry.description %></td>
    <td><%= link_to 'Show', system_nav_entry_path(@system, nav_entry) %></td>
    <td><%= link_to 'Edit', edit_system_nav_entry_path(@system, nav_entry) %></td>
    <td><%= link_to 'Destroy', system_nav_entry_path(@system, nav_entry), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Nav entry', new_system_nav_entry_path(@system) %>

app/views/nav_entries/new.html.erb
<%= link_to 'Back', system_path(@system) %>
<h1>New Nav Entry</h1>

<%= render 'form' %>

app/views/nav_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>System:</b>
  <%= @system.name %>
</p>

<p>
  <b>Parent:</b>
  <%= @nav_entry.parent.content if @nav_entry.parent %>
</p>

<p>
  <b>Seq:</b>
  <%= @nav_entry.seq %>
</p>

<p>
  <b>Content:</b>
  <%= @nav_entry.content %>
</p>

<p>
  <b>Description:</b>
  <%= @nav_entry.description %>
</p>


<%= link_to 'Edit', edit_system_nav_entry_path(@system, @nav_entry) %> |
<%= link_to 'Back', system_nav_entries_path(@system) %>

app/views/systems/_form.html.erb
<%= semantic_form_for(@system) do |f| %>
  <% f.inputs do %>
    <%= f.input :name %>
    <%= f.input :version %>
  <% end %>
  <%= f.buttons :commit %>
<% end %>

app/views/systems/_nav_entry.html.erb
<tr>
  <td>
    <% (indent*5).downto(0) do %>&nbsp;<% end %>
    <%= link_to nav_entry.content, edit_system_nav_entry_path(@system, nav_entry) %>
  </td>
  <td><%= link_to 'New Sub-entry', 
    new_system_nav_entry_path(@system, :parent_id => nav_entry) %></td>
  <td><%= nav_entry.description %></td>
</tr>
<%= render :partial => "nav_entry", :collection => nav_entry.children, 
  :locals => { :indent => indent + 1 } %>

app/views/systems/edit.html.erb
<h1>Editing system</h1>

<%= render 'form' %>

<%= link_to 'Show', @system %> |
<%= link_to 'Back', systems_path %>

app/views/systems/index.html.erb
<h1>Listing systems</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Version</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @systems.each do |system| %>
  <tr>
    <td><%= system.name %></td>
    <td><%= system.version %></td>
    <td><%= link_to 'Show', system %></td>
    <td><%= link_to 'Edit', edit_system_path(system) %></td>
    <td><%= link_to 'Destroy', system, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New System', new_system_path %>

app/views/systems/new.html.erb
<h1>New system</h1>

<%= render 'form' %>

<%= link_to 'Back', systems_path %>

app/views/systems/show.html.erb
<% if notice %><p id="notice"><%= notice %></p><% end %>

<%= link_to 'Edit', edit_system_path(@system) %> |
<%= link_to 'Back', systems_path %>

<h1><%= @system.name %></h1>
<h3>Version: <%= @system.version %></h3>

<p><%= link_to 'New Root Nav Entry', new_system_nav_entry_path(@system) %></p>

<table>
  <%= render :partial => "nav_entry", :collection => @system.roots, :locals => { :indent => 0 } %>
</table>